# Generated by Django 4.0.4 on 2022-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
