# Generated by Django 4.0.4 on 2022-08-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=250)),
                ('priority', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='CaseEntry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('numCases', models.IntegerField()),
                ('numDeaths', models.IntegerField()),
                ('endemic', models.BooleanField()),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('country', 'date')},
            },
        ),
    ]
