# Generated by Django 4.0.4 on 2022-08-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='compDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
