# Generated by Django 4.0.4 on 2022-08-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_compdate_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='compDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
